### ISSUE TITLE
viewLogAction - number of lines

### ISSUE THREAD

**Issue by florinel-chis** [madalinoprea/magneto-debug#15]
```php
$result = Mage::helper('debug')->getLastRows(Mage::getBaseDir('var') . DS . 'log' . DS . $file, 10);
```
The number of lines for exception.log is too low if your stack trace is more than 10 lines... 
One way to deal with this is move 10 to the config (so it can be set to 20-30-whatever) or start from the last line and go back 3 lines from line starting with: #0 
```
012-08-20[...] ERR (3): 
exception 'Exception' with message ....
Stack trace:
#0 /usr/local/zen
```

**Comment by madalinoprea** [comment]
All lines added during current request are going to be listed. See: 47e5d3d97a06c1132b05327e9707622369d14fba
