### ISSUE TITLE
Check if array on admin template

### ISSUE THREAD

**Issue by reesmcivor** [madalinoprea/magneto-debug#22]
app/design/adminhtml/base/default/template/debug/controller.phtml
Just done a modification to line 80 to check if $data is an array before looping it.

line 80: <?php if(is_array($data)) : ?>
line 98: <?php endif; ?>

This error occurred when I installed fooman speedster mod.

**Comment by avra911** [comment]
check: https://github.com/madalinoprea/magneto-debug/pull/34

**Comment by madalinoprea** [comment]
Thanks @avra911
