### ISSUE TITLE
Versioning (git tag)

### ISSUE THREAD

**Issue by clojens** [madalinoprea/magneto-debug#30]
Your current versioned release by means of git tag (`v-1.0.0`) is invalid and causing composer to choke on teh non-semantic versioning/typo as the `-` hyphen causes (removal would suffice).

So please if you could, `v1.0.0` or better yet (if still new) use a `v0.1.0` to reflect earlier development stages (I haven't evaluated the software so I can't say, just noticed this when I wanted to try it out that I couldn't due to aforementioned reason)

p.s. I would create a new repo or rename this one, unless the project is intentionally named after the X-men/Marvel supervillain, in which case, forget I mentioned it ;)

Cheers and keep up the good work :)

**Comment by missoxd** [comment]
Please!!!

**Comment by clockworkgeek** [comment]
:+1:

**Comment by madalinoprea** [comment]
Thanks for suggestion.

I know that I didn't check GitHub for a while but I don't understand why I didn't see any of these issues. Maybe my Gmail rules are too aggressive.

Hopefully my tags will be more composer friendly.

ps: Magneto was inspired from X-Men. Someone dear spent time to create an icon for it :)
