### ISSUE TITLE
Improve support to capture e-mails when common e-mail extensions are installed

### ISSUE THREAD

**Issue by madalinoprea** [madalinoprea/magneto-debug#50]
There are several common extensions that extend same models we do. We need to find a better way to reduce/remove rewrite conflicts conflicts.

**Comment by MrGekko** [comment]
Agreed! I use https://github.com/aschroder/Magento-SMTP-Pro-Email-Extension and https://github.com/fooman/emailattachments

Maybe a handy bit of code to make them work well with this module:
https://github.com/fooman/emailattachments/blob/master/app/code/community/Fooman/EmailAttachments/Model/Core/Email/Queue/Compatibility.php
