### ISSUE TITLE
Review possibilities to implement SQL stack trace

### ISSUE THREAD

**Issue by madalinoprea** [madalinoprea/magneto-debug#51]
It would be interesting to show code that is responsible to generate a specific SQL.

Long time ago when I've checked this possibility, implementation involved overwriting some Zend classes. Lets see if anything changed since then. We need something simple and production safe (people should not be able to commit this change into production).

**Comment by sandermangel** [comment]
@madalinoprea this would be great. Really could have used this feature yesterday during debugging.
is integrating https://github.com/danslo/Danslo_Aop an option so any method/class can be wrapped? Would prevent overwriting of classes

**Comment by madalinoprea** [comment]
Thanks @sandermangel. I didn't know about this module but it looks really promising.

**Comment by madalinoprea** [comment]
I've looked at Danslo_Aop but I don't like the idea that we will have to depend on 'gaaop/framework.

But we're good. We have a simpler alternative: use a custom Zend_Db_Profiler.
 - create a configuration that enables sql stack trace
 - Magento doesn't pass profiler class configuration to Zend_Db, so we have to add it via an observer as soon as possible (e.g onControllerFrontInitBefore)
- Record the stack trace (maybe we need to have also our version of Zend_Db_Profiler_Query; we cannot associate stack trace directly on those type of instances)
- persist the stack trace if in queries (we might end up with objects with different interfaces in \Sheep_Debug_Model_RequestInfo::initQueries, some will be of 

Similar approach is used by Zend_Db_Profiler_Firebug

**Comment by sandermangel** [comment]
@madalinoprea makes sense, I'll do some tests next week when I have some time on my hands. 
My biggest 'worry' is that using observers we're gonna miss out on some queries

**Comment by madalinoprea** [comment]
I believe we will lost stack traces for some queries. I hope they are not too many in that important.

I've pushed some changes to have an workable prototype:

![screen shot 2016-03-11 at 10 16 24](https://cloud.githubusercontent.com/assets/605494/13696909/5c152de8-e772-11e5-8ff4-df65aea19dcd.png)


Also we should try trim Magento root directory from referenced file.

**Comment by sandermangel** [comment]
this is awesome! Path can be removed indeed
