### ISSUE TITLE
Template hints not showing through toolbar

### ISSUE THREAD

**Issue by Hobbit78** [madalinoprea/magneto-debug#52]
Just updated to the latest version. Toolbar works good to me except the template hints. Somehow they're not showing up. The do show up in the back-end when I enable them through the toolbar.

When I enable them throught the back-end it works fine.

**Comment by madalinoprea** [comment]
Hi @Hobbit78 ,

Can you run this query and attach the results?

`select * from core_config_data where path like 'dev/debug/template_hints%';`

Latest version is updating template hints configuration only on 'default' scope. We're trying to use only a single configuration to enable/disable template hints on backend and on all available stores.

I assume you have these configuration overwritten at store level. My recommendation is to remove template hints related configurations specified at:
`delete from core_config_data where path like 'dev/debug/template_hints%' and scope!= 'default';`

Cheers,
Mario

**Comment by Hobbit78** [comment]
Hi Mario,

There ya go.
`config_id	scope	scope_id	path	value
1139	default	0	dev/debug/template_hints	1
1140	default	0	dev/debug/template_hints_blocks	1
1225	stores	1	dev/debug/template_hints	0
1226	stores	1	dev/debug/template_hints_blocks	0
1395	websites	1	dev/debug/template_hints	0
1396	websites	1	dev/debug/template_hints_blocks	0`

**Comment by Hobbit78** [comment]
Hi Mario,

Thanks!
Removing the templates with `delete from core_config_data where path like 'dev/debug/template_hints%' and scope!= 'default'` did the job.

Great to see people working at this great tool again! Keep up the good work!

Cheers!
Pierre

**Comment by madalinoprea** [comment]
Hi Pierre,

Thanks for your feedback. I've pushed some changes that should prevent this issue for other users. 

We've resumed working on this extension few weeks ago after many many years and we hope to be able to dedicate more time in next period.

Thanks,
Mario
