### ISSUE TITLE
Nginx compatible "undefined function getallheaders()"

### ISSUE THREAD

**Issue by MrGekko** [madalinoprea/magneto-debug#56]
Uncaught Error: Call to undefined function getallheaders() in /vendor/madalinoprea/magneto-debug/code/Debug/Model/Controller.php:47

The function getallheaders does not exist when using Nginx.
This polyfill fixes it:
https://github.com/ralouphie/getallheaders

**Comment by madalinoprea** [comment]
Thanks Justin for pointing the solution.

I've committed some changes into a dev branch that should be released in the following days. We already had some code pushed in this area.

Cheers,
Mario
