### ISSUE TITLE
Make it compatible for Magento CE 1.7 / Magento EE 1.12

### ISSUE THREAD

**Issue by madalinoprea** [madalinoprea/magneto-debug#57]
Currently we don't plan to spent any time on this issue. Please let us know if you're on any of these Magento version and we'll take a look.

For now we know at least one error that needs to be addressed for Magento CE 1.7:
`.PHP Fatal error:  Call to undefined method Mock_Magento_Db_Adapter_Pdo_Mysql_3fc14b29::delete() in /home/travis/build/madalinoprea/magneto-debug/code/Debug/Model/Service.php on line 215
`

**Comment by lfolco** [comment]
I'm using 1.7 and would like to see it fixed.

**Comment by madalinoprea** [comment]
Hi @lfolco ,

I've added compatibility for Magento CE 1.7 (I assume is ok for Magento EE 1.12 but I didn't test it). These code is going to be released tomorrow as part of version 1.5.1

![screen shot 2016-03-03 at 21 50 52](https://cloud.githubusercontent.com/assets/605494/13507185/382386fc-e18a-11e5-9811-7fbb6ad0bea1.png)

**Comment by lfolco** [comment]
awesome, thanks!
