### ISSUE TITLE
Purpose of thrown error in Model/Block ("is already marked as rendered")

### ISSUE THREAD

**Issue by sandermangel** [madalinoprea/magneto-debug#66]
Could you tell me what the reason is for the thrown error in https://github.com/madalinoprea/magneto-debug/blob/master/code/Debug/Model/Block.php#L56 ?

I ran into some issues getting that on certain pages, still debugging what caused in but it originates from the Innoext_Warehouse module. Still, not sure why it needs to be a fatal error instead of perhaps a warning in a log? #

**Comment by steffen-wirth** [comment]
I'm having the same issue with Mod_Baseprice & IWD_Onepage_Checkout Extensions

**Comment by sandermangel** [comment]
@steffen-wirth any one of those free? I want to work on a PR for this issue this weekend. Would be nice to have multiple modules to test

**Comment by steffen-wirth** [comment]
@sandermangel yes both are free. here's a copy of https://github.com/simkea/DerModPro_BasePrice and IWD Onepage Checkout you can download from https://www.iwdagency.com/

**Comment by steffen-wirth** [comment]
found a better one for DerModPro_BasePrice https://github.com/riker09/DMP_BasePrice/commits/master

**Comment by sandermangel** [comment]
@steffen-wirth thanks, will work on it this weekend. Shouldn't be too much trouble to make a nice PR
