### ISSUE TITLE
Call to undefined method Zend_Mime_Part::getRawContent()

### ISSUE THREAD

**Issue by didesignbg** [madalinoprea/magneto-debug#75]
Hi, thanks for the great module.
I get the following Fatal error: Call to undefined method Zend_Mime_Part::getRawContent() in /var/www/.modman/magneto-debug/code/Debug/Model/Core/Email/Template.php on line 105 
Magento 1.7.0.2, PHP 5.6, this happens when magent sends a welcome email to new user. I've checked the class Zend_Mime_Part located at lib/Zend/Mime/Part.php and sure enough it doesn't have method getRawContent(), only getContent().
Am I missing something?
getRawContent() seems to be introduced with Zend Framework 1.12, I am not sure but this translate to Magento 1.9 and up.

**Comment by madalinoprea** [comment]
Hi @didesignbg, 

You're absolutely right: getRawContent() method is not available on Zend Framework 1.11 that is used by Magento CE 1.7. Unit test didn't help to catch this error.

Thanks for reporting this problem. I've pushed a fix in release 1.6.2.

Thanks,
Mario

**Comment by didesignbg** [comment]
Thank you Mario, just tested and it works like a charm. Great support.
