### ISSUE TITLE
suggestion : a dedicated option to disable $this->getRequestInfo()->save();

### ISSUE THREAD

**Issue by tbondois** [madalinoprea/magneto-debug#76]
Hello,

I find irrelevant that by default, a debug toolbar insert in db lot of data on each call. The response can be big, in case of ajax call for example. 
I speak about this insert : $this->getRequestInfo()->save() in Model/Observer.php

Did you think about a dedicated option to enable/disable inserts in sheep_debug_request_info ?

Cherry on the cake : also an option to truncate this table :)

**Comment by madalinoprea** [comment]
Hi @tbondois,

I've considered to disable persistence but I need a least a temporary storage to store detailed information. I'll look to see what are advantages and cons to use Magento cache storage as an alternative storage source.

Right now there is a config that disables persistence but I didn't test lately and I don't know its probable  side effects:  https://github.com/madalinoprea/magneto-debug/blob/master/code/Debug/Model/Observer.php#L160

We have at least two cherries :) 
- we have a Magento cron job that deletes saved data after one day (number of days can be changed): https://github.com/madalinoprea/magneto-debug/blob/master/code/Debug/etc/config.xml#L217
- we're aware that Magento cron jobs are not always running on dev environments so we also have a 'Purge All' button

![screen shot 2016-03-22 at 22 26 20](https://cloud.githubusercontent.com/assets/605494/13966894/3725f74c-f07d-11e5-9dda-d3d551455851.png)

How annoying is for you to have this save? What are its main problems?

Cheers,
Mario

**Comment by tbondois** [comment]
Yes I saw the configuration thing. Problem is that if you want to quicky re-enable hit, it's not quick :)


How annoying is for you to have this save? What are its main problems?

> I Have some projects full of ajax, so with big responses
> Sometimes I have some "Mysql gone away" because of the amount of request. I don't want to have a doubr about if it's a debug module who do that (and participate to that)
> On collaborative projects, others devs can see that as a work tracker.
> For my need, of a debug toobar, storing debug information in db is.. useless. Almost all of time. But I appreciate having the possibility to do that. 

See on my https://github.com/tbondois/magento1devkit in Helper/Data.php I made a *superquick* (and a little dirty) fix.The only thing it's don't do now is displaying the most / last report in the extended panel of the toolbar. Else everything work fine, except maybe the SQL profiler that I didn't try.

So in my fork, by default it's disabled, but I can -enable/disable it if I need, on-the-fly. And in the utilities.phtml I add a menu entry to enable / disable. That's MY specific need, but I was just here to make a suggestion.

**Comment by madalinoprea** [comment]
@tbondois I'll work on adding the ability to enable/disable capturing. It makes sense. I'm avid user of xdebug but I  enable it  on demand because it adds to much overhead.

I'll take a look at your branch. Currently I see this feature requiring the following steps:
- Add 'Enable/Disable Capture' entry under Tools menu
- When menu is clicked add/remove cookie
- Update canPersist() to take into account this new cookie
- Possible conflicts:
-- for projects that use full page caching but I assume most of the developer have that FPC disabled

**Comment by madalinoprea** [comment]
I've added some implementation for this feature. I'll test it to see how other areas are impacted and maybe maybe we're going to release this friday :tada: 

![image](https://cloud.githubusercontent.com/assets/605494/14490164/f4b8163e-0179-11e6-906d-9cd3a04e0715.png)

**Comment by tbondois** [comment]
Nice :)

I make almost the same algorythm you describe on my fork 3 weeks ago - but in a dirtier way, for sure :D 
And I noticed that when I disabled persistance, the extended panels didn't work (when you clic on a entry on the left). Think to test that ^^

NB : on https://github.com/tbondois/magento1devkit/commit/617c4b11bd680142b651b5b149a3bb30c9b6cef2 in getRouteStoreId() as you can see I also fixed a Store problem because I saw that when I was in a non-default store, the urls was bad.

**Comment by madalinoprea** [comment]
@tbondois, what do you mean by extended panels? Do you refer to detail view? That is not going to work because that view is in another request and to work it needs all these information persisted.

An option would be to use short lifetime cache keys for temporary storage.

**Comment by tbondois** [comment]
> Do you refer to detail view?

Yes. If I will need it I can enable the persistance, it's not a problem, it was just to notice you about possible problems.
