### ISSUE TITLE
Magento Downloader Fatal Error

### ISSUE THREAD

**Issue by devzorg** [madalinoprea/magneto-debug#78]
PHP message: PHP Fatal error:  Call to a member function getSessionId() on null in *****/.modman/magneto-debug/code/Debug/Model/RequestInfo.php on line 505" while reading response header from upstream, client: *********, server: *********, request: "POST /downloader/index.php?A=cleanCache

Looks like Sheep injects even to downloader :) need to exclude this I guess

**Comment by madalinoprea** [comment]
Hi @devzorg,

Thanks for reporting this. I've committed some fixes that will resolve fatal errors. This is going to be included in our weekly release.

There is another ticket that will address on-demand capturing and probably whitelisting/blacklisting requests.

Cheers,
Mario
