### ISSUE TITLE
Extension breaks wishlist

### ISSUE THREAD

**Issue by michaelzangerle** [madalinoprea/magneto-debug#82]
When the extension is enabled and I access the wishlist page I get following error:

```
Fatal error: Call to a member function getProduct() on null in [...]/app/code/core/Mage/Wishlist/Block/Customer/Wishlist/Item/Options.php on line 117
```

For some reason $item is null when the extension is enabled - when I disable the extension it works fine.
I could patch the Options.php file but I am not quite sure if this is the way to go as it works fine without the extension.

Magento ver. 1.9.2.1
Latest version of magneto-debug

**Comment by madalinoprea** [comment]
Thanks @michaelzangerle for reporting this. I've also noticed this several times and I didn't image was caused by this extension.

I'll take a look and find a solution to resolve this unwanted side effect.

**Comment by michaelzangerle** [comment]
Thanks!
