### ISSUE TITLE
PHPUnit issue with MagentoEE 1.14

### ISSUE THREAD

**Issue by bkibilko** [madalinoprea/magneto-debug#83]
I just pulled the newest changes from master branch and I got this error after running unit tests:

> vagrant@vagrant:[/var/magento_up/current/magento]: phpunit
> PHPUnit 4.8.26 by Sebastian Bergmann and contributors.
> Warning:        Deprecated configuration setting "strict" used
> 
> PHP Fatal error:  Uncaught exception 'Exception' with message 'Warning: session_start(): Cannot send session cookie - headers already sent by (output started at phar:///usr/local/bin/phpunit/phpunit/Util/Printer.php:134)  in /var/magento_up/current/magento/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php on line 133' in /var/magento_up/current/magento/app/code/core/Mage/Core/functions.php:245
> Stack trace:
> #0 [internal function]: mageCoreErrorHandler(2, 'session_start()...', '/var/magento_up...', 133, Array) #1 /var/magento_up/current/magento/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php(133): session_start()
> #2 /var/magento_up/current/magento/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php(222): Mage_Core_Model_Session_Abstract_Varien->start(NULL)
> #3 /var/magento_up/current/magento/app/code/core/Mage/Core/Model/Session/Abstract.php(84): Mage_Core_Model_Session_Abstract_Varien->init('core', NULL)
> #4 /var/magento_up/current/magento/app/code/core/Mage/Core/Model/Session.php(42): Mage_Core_Model_Sess in /var/magento_up/current/magento/app/code/core/Mage/Core/functions.php on line 245
> PHP Fatal error:  Call to a member function endRequest() on a non-object in /var/magento_up/current/.modman/Magento_Debug/code/Debug/Model/RequestInfo.php on line 92
> PHP Stack trace:
> PHP   1. Sheep_Debug_Model_Observer->shutdown() /var/magento_up/current/.modman/Magento_Debug/code/Debug/Model/Observer.php:0
> PHP   2. Sheep_Debug_Model_Observer->updateProfiling() /var/magento_up/current/.modman/Magento_Debug/code/Debug/Model/Observer.php:149
> PHP   3. Sheep_Debug_Model_RequestInfo->completeLogging() /var/magento_up/current/.modman/Magento_Debug/code/Debug/Model/Observer.php:126

More details:
CentOS 7.2 on vagrant
PHP 5.4.16
PHPUnit 4.8.26
Magento 1.14.2.4

**Comment by bkibilko** [comment]
I fixed session issue according to this blog post http://mmenozzi.github.io/2015/07/21/session-handling-while-testing-magento-with-ecomdev-phpunit/ , but I'm not sure if issue can be closed. In my opinion, it shouldn't happen.

**Comment by madalinoprea** [comment]
Hi @bkibilko , I'll take a look to see if  I can reproduce same error. This looks familiar. I believe I use a custom phpunit configuration file.

Can you check if you have same error with this configuration file: https://github.com/madalinoprea/magneto-debug/commit/09f0d3e3d063b2160ed1bc436afca1070f3e0a71

**Comment by bkibilko** [comment]
Hi @madalinoprea, 
It works fine with this configuration file :), but I have to placed it to magento folder to run phpunit without parameters. May I suggest add this to modman file? I can create a pull request
:+1:

**Comment by madalinoprea** [comment]
Happy that your issue got resolved. I'm against your solution because people might have their own configuration files and it will not be nice to automatically overwrite them :)

I've added this error in 'Common Issues' section from Readme.
