### ISSUE TITLE
Template Hints Works in admin side but not in Frontend side.

### ISSUE THREAD

**Issue by progammer-rkt** [madalinoprea/magneto-debug#84]
Hi,

I have a weird issue here. I 'modman'ed this extension to my local magento site. But Template hints enabling/disabling from toolbar is not working in frontend, but it works in admin section!

I tried `delete from core_config_data where path like 'dev/debug/template_hints%' and scope!= 'default';` but it is not working.

Please let me know how can I dig it out this issue. Thank you.

**Comment by madalinoprea** [comment]
Hi @progammer-rkt , 

I see two reasons why this might occur:

1. You're using a custom theme on frontend that removed or overwrote layout update that is responsible to add before_body_end block. 

You can check if toolbar is visible when using the out of the box theme to confirm is theme issue and then to manually re-add the block and check what other functionality was suppressed by removing that block.

> Toolbar is added to all pages that have a structural block named before_body_end. By default this block is available on all Magento pages. Eliminate a possible cache problem by disabling all caches. Try to determine if there are any customizations that have removed before_body_end.

1. Allow Symlinks configuration required by modman is enabled only on admin. This is not very common.

Review allow symlinks configurations:
```sql
select * from core_config_data where path like '%allow_symlink%';
```

![image](https://cloud.githubusercontent.com/assets/605494/16354314/1e959c2c-3a98-11e6-8dbe-34139a9fcba6.png)


- Toolbar is added to all pages that have a structural block named before_body_end. By default this block is available on all Magento pages. Eliminate a possible cache problem by disabling all caches. Try to determine if there are any customizations that have removed before_body_end.
