### ISSUE TITLE
Sheep Debug causes early Session-ID initialization (PHPSESSID)

### ISSUE THREAD

**Issue by possi** [madalinoprea/magneto-debug#86]
http://alanstorm.com/magento_sessions_early

While Sheep-Debug is enabled, magento frontend and adminhtml both creates a PHPSESSID session-cookie instead of frontend/adminhtml.
This is because the observer onControllerFrontInitBefore() calls Sheep_Debug_Model_Controller->init() which tries to get the current encryptedSessionId.

![image](https://cloud.githubusercontent.com/assets/1308937/16079980/aa8f4258-3306-11e6-97df-ca27c0f4134f.png)

**Comment by madalinoprea** [comment]
Thanks @possi for pointing this error. I didn't notice it but probably I've blamed Magento for some weirdnesses.

I've committed a fix that is going to be included in the next release scheduled for early next week.
