### ISSUE TITLE
Exception "Disable profiler first!"

### ISSUE THREAD

**Issue by proxium** [madalinoprea/magneto-debug#97]
When enabling the profiler from the toolbar this exception appears (I'm using Magento 1.9.3.2 + Sheep_Debug 1.8.1):

2017/02/13 16:45:12 [error] 7009#0: *19 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Disable profiler first!' in /var/www/sites/magento/src/app/code/community/Varien/Profiler.php:491
Stack trace:
#0 /var/www/sites/magento/src/app/code/community/Varien/Profiler.php(584): Varien_Profiler::getStackLog()
#1 /var/www/sites/magento/src/app/code/local/Schlafen/Shop/Model/Debug/Observer.php(42): Varien_Profiler::getTimers()
#2 /var/www/sites/magento/src/app/code/community/Sheep/Debug/Model/Observer.php(154): Schlafen_Shop_Model_Debug_Observer->updateProfiling()
#3 [internal function]: Sheep_Debug_Model_Observer->shutdown()
#4 {main}
  thrown in /var/www/sites/magento/src/app/code/community/Varien/Profiler.php on line 491
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/sites/magento/src/index.php:0
PHP message: PHP   2. Mage::run() /var/www/sites/magento/src/index.php:83
PHP message: PHP   3. Mage::printException() /var/www/sites/magento/src/app/Mage.php:694" while reading response header from upstream, client: 127.0.0.1, server: www.magento.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.magento.dev"

**Comment by deepanshu27193** [comment]
@proxium have you installed any other extension for profiling like Aoe_Profiler etc. If yes, try disable or uninstalling them once.

**Comment by dudzio12** [comment]
Aoe_Profiler implements Varien_Profiler class. Make sure it's also deleted from app/code/community dir.

**Comment by kkrieger85** [comment]
Hi, 

i faced this exception even after disabling Aoe_Profiler. What else could cause that? 

Thx

**Comment by madalinoprea** [comment]
This exception is raised by https://github.com/AOEpeople/Aoe_Profiler/blob/dd9fdf94879e687c2bb5140229910450c46e8f7f/app/code/community/Varien/Profiler.php#L491 so maybe you didn't completely disabled Aoe_Profiler. Maybe Magento compilation  needs to be refreshed?!

Why exception is raised? This module, by default, is enabling Magento profiler to fetch some details: https://github.com/madalinoprea/magneto-debug/blob/master/code/Debug/Model/Observer.php#L97

If you want to keep both modules you might try to disable automatic enabling by setting config `sheep_debug/options/force_varien_profile` to 0 (via XML or database, probably Admin is not accessible).

By default is set to 1: https://github.com/madalinoprea/magneto-debug/blob/master/code/Debug/etc/config.xml#L230

**Comment by proxium** [comment]
I confirm that setting the configuration via n98-magerun.phar (because Admin was not accessible)

    n98-magerun.phar config:set --scope=default --scope-id=0 sheep_debug/options/force_varien_profile 0

had fixed the issue
